### ISSUE TITLE
"ImportError: No module named extern" caused by "from pkg_resources.extern import packaging"

### ISSUE THREAD

**Issue by hangtwenty** [ajk8/hatchery#5]
```
$ hatchery test -s
Traceback (most recent call last):
  File "/Users/me/.virtualenvs/xyz/bin/hatchery", line 7, in <module>
    from hatchery.main import hatchery
  File "/Users/me/.virtualenvs/xyz/lib/python2.7/site-packages/hatchery/main.py", line 71, in <module>
    from . import project
  File "/Users/me/.virtualenvs/xyz/lib/python2.7/site-packages/hatchery/project.py", line 8, in <module>
    from pkg_resources.extern import packaging
ImportError: No module named extern
```

this seems correct..?

```
In [3]: dir(pkg_resources)
Out[3]:
# SNIPPED
 'absolute_import',
 'add_activation_listener',
 'cached_files',
 'cleanup_resources',
 'collections',
 'compatible_platforms',
 'darwinVersionString',
 'declare_namespace',
 'email',
 'empty_provider',
 'ensure_directory',
 'evaluate_marker',
 'extraction_error',
 'extraction_path',
 'file_ns_handler',
 'find_distributions',
 'find_eggs_in_zip',
 'find_nothing',
 'find_on_path',
 # SNIPPED
```

----

versions:

```
$ python --version
Python 2.7.10
```

```
hatchery==0.4
```

```
In [4]: import setuptools

In [5]: setuptools.__version__
Out[5]: '18.2'
```

**Comment by hangtwenty** [comment]
## Fix: upgrade `setuptools`

```
$ pip install -U setuptools
Collecting setuptools
  Using cached setuptools-28.8.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed setuptools-28.8.0
```
